name: Sync Labels

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync labels to multiple repos
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          repository: |
            SynergyX-AI-Pattern/SynergyX-ML-Server
            SynergyX-AI-Pattern/SynergyX-Backend
            SynergyX-AI-Pattern/SynergyX-Frontend
          file: ./labels.yml
          token: ${{ secrets.PERSONAL_TOKEN }}
